#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-uber
Version  : 0.0.15
Release  : 9
URL      : https://rubygems.org/downloads/uber-0.0.15.gem
Source0  : https://rubygems.org/downloads/uber-0.0.15.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-bundler
BuildRequires : rubygem-i18n
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-thread_safe
BuildRequires : rubygem-tzinfo

%description
# Uber
_Gem-authoring tools like class method inheritance in modules, dynamic options and more._

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n uber-0.0.15
gem spec %{SOURCE0} -l --ruby > rubygem-uber.gemspec

%build
gem build rubygem-uber.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
uber-0.0.15.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/uber-0.0.15
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/uber-0.0.15.gem
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/Gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/README.md
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/callable.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/delegates.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/inheritable_attr.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/uber_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/lib/uber/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/builder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/delegates_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/inheritable_attr_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/inheritance_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/version_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/test/zeugs.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.15/uber.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/uber-0.0.15.gemspec
