#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-uber
Version  : 0.0.13
Release  : 6
URL      : ttps://rubygems.org/downloads/uber-0.0.13.gem
Source0  : ttps://rubygems.org/downloads/uber-0.0.13.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-i18n
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Uber
_Gem-authoring tools like class method inheritance in modules, dynamic options and more._

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n uber-0.0.13
gem spec %{SOURCE0} -l --ruby > rubygem-uber.gemspec

%build
gem build rubygem-uber.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
uber-0.0.13.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/uber-0.0.13.gem
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/README.md
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/callable.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/delegates.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/inheritable_attr.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/uber_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/lib/uber/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/builder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/delegates_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/inheritable_attr_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/inheritance_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/version_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/test/zeugs.rb
/usr/lib64/ruby/gems/2.3.0/gems/uber-0.0.13/uber.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/uber-0.0.13.gemspec
